"""DDA Python Bindings

This package provides Python bindings for DDA (Delay Differential Analysis).

Example usage:
    from dda_py import DDARequest, DDARunner, ST, generate_select_mask
"""

# Import from variants module (generated by dda-codegen)
from .variants import (
    SPEC_VERSION,
    SELECT_MASK_SIZE,
    BINARY_NAME,
    REQUIRES_SHELL_WRAPPER,
    SHELL_COMMAND,
    SUPPORTED_PLATFORMS,
    ChannelFormat,
    FileType,
    OutputColumns,
    VariantMetadata,
    ST,
    CT,
    CD,
    RESERVED,
    DE,
    SY,
    VARIANT_REGISTRY,
    VARIANT_ORDER,
    SelectMaskPositions,
    get_variant_by_abbrev,
    get_variant_by_suffix,
    get_variant_by_position,
    active_variants,
    generate_select_mask,
    parse_select_mask,
    format_select_mask,
    DEFAULT_DELAYS,
)

# Import from runner module (DDARunner, DDARequest)
from .runner import (
    DDARunner,
    DDARequest,
    Flags,
    Defaults,
)

__all__ = [
    # Spec constants
    "SPEC_VERSION",
    "SELECT_MASK_SIZE",
    "BINARY_NAME",
    "REQUIRES_SHELL_WRAPPER",
    "SHELL_COMMAND",
    "SUPPORTED_PLATFORMS",
    # Types
    "ChannelFormat",
    "FileType",
    "OutputColumns",
    "VariantMetadata",
    # Variant instances
    "ST",
    "CT",
    "CD",
    "RESERVED",
    "DE",
    "SY",
    # Registries
    "VARIANT_REGISTRY",
    "VARIANT_ORDER",
    "SelectMaskPositions",
    # Functions
    "get_variant_by_abbrev",
    "get_variant_by_suffix",
    "get_variant_by_position",
    "active_variants",
    "generate_select_mask",
    "parse_select_mask",
    "format_select_mask",
    # Delays
    "DEFAULT_DELAYS",
    # DDA Execution
    "DDARunner",
    "DDARequest",
    "Flags",
    "Defaults",
]

__version__ = "1.0.0"
