"""DDA Python Bindings

Python interface for Delay Differential Analysis (DDA).

High-level API (recommended)::

    import numpy as np
    from dda_py import run_st

    data = np.random.randn(3, 10000)
    result = run_st(data, sfreq=256.0, delays=(7, 10), wl=200, ws=100)
    print(result.coefficients.shape)
    print(result.to_dataframe().head())

Low-level API::

    from dda_py import DDARequest, DDARunner, ST, generate_select_mask

    request = DDARequest(
        file_path="data.edf",
        channels=[0, 1, 2],
        variants=["ST"],
        window_length=200,
        window_step=100,
        delays=[7, 10],
    )
    runner = DDARunner()
    result = runner.run(request)
"""

# Import from variants module (generated by dda-codegen)
# Import from runner module (DDARunner, DDARequest)
from .runner import (
    DDARequest,
    DDARunner,
    Defaults,
    Flags,
)
from .variants import (
    BINARY_NAME,
    CD,
    CT,
    DE,
    DEFAULT_DELAYS,
    REQUIRES_SHELL_WRAPPER,
    RESERVED,
    SELECT_MASK_SIZE,
    SHELL_COMMAND,
    SPEC_VERSION,
    ST,
    SUPPORTED_PLATFORMS,
    SY,
    VARIANT_ORDER,
    VARIANT_REGISTRY,
    ChannelFormat,
    FileType,
    OutputColumns,
    SelectMaskPositions,
    VariantMetadata,
    active_variants,
    format_select_mask,
    generate_select_mask,
    get_variant_by_abbrev,
    get_variant_by_position,
    get_variant_by_suffix,
    parse_select_mask,
)

# Import result types
from .results import (
    STResult,
    CTResult,
    DEResult,
)

# Import high-level API
from .api import (
    run_st,
    run_ct,
    run_de,
)

# Import model encoding utilities
from .model_encoding import (
    generate_monomials,
    monomial_to_text,
    monomial_to_latex,
    decode_model_encoding,
    visualize_model_space,
    model_encoding_to_dict,
)

# Import batch processing
from .batch import (
    GroupResult,
    run_batch,
    collect_results,
)

# Import statistics
from .stats import (
    PermutationResult,
    EffectSizeResult,
    WindowComparisonResult,
    permutation_test,
    compare_windows,
    compute_effect_size,
)

# Import plotting (lazy — matplotlib only imported when functions are called)
from .plotting import (
    plot_coefficients,
    plot_errors,
    plot_heatmap,
    plot_ergodicity,
    plot_model,
)

# Import BIDS integration (lazy — mne-bids only imported when functions are called)
from .bids import (
    BIDSRecording,
    find_recordings,
    run_bids,
)

__all__ = [
    # Spec constants
    "SPEC_VERSION",
    "SELECT_MASK_SIZE",
    "BINARY_NAME",
    "REQUIRES_SHELL_WRAPPER",
    "SHELL_COMMAND",
    "SUPPORTED_PLATFORMS",
    # Types
    "ChannelFormat",
    "FileType",
    "OutputColumns",
    "VariantMetadata",
    # Variant instances
    "ST",
    "CT",
    "CD",
    "RESERVED",
    "DE",
    "SY",
    # Registries
    "VARIANT_REGISTRY",
    "VARIANT_ORDER",
    "SelectMaskPositions",
    # Functions
    "get_variant_by_abbrev",
    "get_variant_by_suffix",
    "get_variant_by_position",
    "active_variants",
    "generate_select_mask",
    "parse_select_mask",
    "format_select_mask",
    # Delays
    "DEFAULT_DELAYS",
    # Low-level execution
    "DDARunner",
    "DDARequest",
    "Flags",
    "Defaults",
    # Result types
    "STResult",
    "CTResult",
    "DEResult",
    # High-level API
    "run_st",
    "run_ct",
    "run_de",
    # Model encoding
    "generate_monomials",
    "monomial_to_text",
    "monomial_to_latex",
    "decode_model_encoding",
    "visualize_model_space",
    "model_encoding_to_dict",
    # Batch processing
    "GroupResult",
    "run_batch",
    "collect_results",
    # Statistics
    "PermutationResult",
    "EffectSizeResult",
    "WindowComparisonResult",
    "permutation_test",
    "compare_windows",
    "compute_effect_size",
    # Plotting
    "plot_coefficients",
    "plot_errors",
    "plot_heatmap",
    "plot_ergodicity",
    "plot_model",
    # BIDS integration
    "BIDSRecording",
    "find_recordings",
    "run_bids",
]

__version__ = "0.4.0"
