"""Backwards compatibility module.

Re-exports everything from the main package for tests that import from dda_py.generated.
"""
from .variants import (
    SPEC_VERSION,
    SELECT_MASK_SIZE,
    BINARY_NAME,
    REQUIRES_SHELL_WRAPPER,
    SHELL_COMMAND,
    SUPPORTED_PLATFORMS,
    ChannelFormat,
    FileType,
    OutputColumns,
    VariantMetadata,
    ST,
    CT,
    CD,
    RESERVED,
    DE,
    SY,
    VARIANT_REGISTRY,
    VARIANT_ORDER,
    SelectMaskPositions,
    get_variant_by_abbrev,
    get_variant_by_suffix,
    get_variant_by_position,
    active_variants,
    generate_select_mask,
    parse_select_mask,
    format_select_mask,
    DEFAULT_DELAYS,
)

from .runner import (
    DDARunner,
    DDARequest,
    Flags,
    Defaults,
)

__all__ = [
    "SPEC_VERSION",
    "SELECT_MASK_SIZE",
    "BINARY_NAME",
    "REQUIRES_SHELL_WRAPPER",
    "SHELL_COMMAND",
    "SUPPORTED_PLATFORMS",
    "ChannelFormat",
    "FileType",
    "OutputColumns",
    "VariantMetadata",
    "ST",
    "CT",
    "CD",
    "RESERVED",
    "DE",
    "SY",
    "VARIANT_REGISTRY",
    "VARIANT_ORDER",
    "SelectMaskPositions",
    "get_variant_by_abbrev",
    "get_variant_by_suffix",
    "get_variant_by_position",
    "active_variants",
    "generate_select_mask",
    "parse_select_mask",
    "format_select_mask",
    "DEFAULT_DELAYS",
    "DDARunner",
    "DDARequest",
    "Flags",
    "Defaults",
]
