"""Backwards compatibility module.

Re-exports everything from the main package for tests that import from dda_py.generated.
"""

from .api import (
    run_ct,
    run_de,
    run_st,
)
from .batch import (
    GroupResult,
    collect_results,
    run_batch,
)
from .bids import (
    BIDSRecording,
    find_recordings,
    run_bids,
)
from .model_encoding import (
    decode_model_encoding,
    generate_monomials,
    model_encoding_to_dict,
    model_matrix_to_encoding,
    monomial_to_latex,
    monomial_to_text,
    visualize_model_space,
)
from .plotting import (
    plot_coefficients,
    plot_ergodicity,
    plot_errors,
    plot_heatmap,
    plot_model,
)
from .results import (
    CTResult,
    DDAResult,
    DelayParameters,
    DEResult,
    STResult,
    VariantResultData,
    WindowParameters,
)
from .runner import (
    DDARequest,
    DDARunner,
    Defaults,
    Flags,
    build_command_string,
    run_DDA,
)
from .stats import (
    EffectSizeResult,
    PermutationResult,
    WindowComparisonResult,
    compare_windows,
    compute_effect_size,
    permutation_test,
)
from .structure_selection import (
    StructureSelectionResult,
    StructureSelectionTrial,
    structure_selection,
)
from .variants import (
    BINARY_NAME,
    CD,
    CT,
    DE,
    DEFAULT_DELAYS,
    REQUIRES_SHELL_WRAPPER,
    RESERVED,
    SELECT_MASK_SIZE,
    SHELL_COMMAND,
    SPEC_VERSION,
    ST,
    SUPPORTED_PLATFORMS,
    SY,
    VARIANT_ORDER,
    VARIANT_REGISTRY,
    ChannelFormat,
    FileType,
    OutputColumns,
    SelectMaskPositions,
    VariantMetadata,
    active_variants,
    format_select_mask,
    generate_select_mask,
    get_variant_by_abbrev,
    get_variant_by_position,
    get_variant_by_suffix,
    parse_select_mask,
)

__all__ = [
    "SPEC_VERSION",
    "SELECT_MASK_SIZE",
    "BINARY_NAME",
    "REQUIRES_SHELL_WRAPPER",
    "SHELL_COMMAND",
    "SUPPORTED_PLATFORMS",
    "ChannelFormat",
    "FileType",
    "OutputColumns",
    "VariantMetadata",
    "ST",
    "CT",
    "CD",
    "RESERVED",
    "DE",
    "SY",
    "VARIANT_REGISTRY",
    "VARIANT_ORDER",
    "SelectMaskPositions",
    "get_variant_by_abbrev",
    "get_variant_by_suffix",
    "get_variant_by_position",
    "active_variants",
    "generate_select_mask",
    "parse_select_mask",
    "format_select_mask",
    "DEFAULT_DELAYS",
    "DDARunner",
    "DDARequest",
    "Flags",
    "Defaults",
    "build_command_string",
    "run_DDA",
    "DDAResult",
    "DelayParameters",
    "STResult",
    "CTResult",
    "DEResult",
    "VariantResultData",
    "WindowParameters",
    "run_st",
    "run_ct",
    "run_de",
    "generate_monomials",
    "model_matrix_to_encoding",
    "monomial_to_text",
    "monomial_to_latex",
    "decode_model_encoding",
    "visualize_model_space",
    "model_encoding_to_dict",
    "GroupResult",
    "run_batch",
    "collect_results",
    "PermutationResult",
    "EffectSizeResult",
    "WindowComparisonResult",
    "permutation_test",
    "compare_windows",
    "compute_effect_size",
    "StructureSelectionTrial",
    "StructureSelectionResult",
    "structure_selection",
    "plot_coefficients",
    "plot_errors",
    "plot_heatmap",
    "plot_ergodicity",
    "plot_model",
    "BIDSRecording",
    "find_recordings",
    "run_bids",
]
